function DelayCalc()
Times=9;
Period=1;
BurstU=1;
FeedbackDelay=1;
ArrivalRate=0.2;
ServiceRateL=1/Period;
ServiceRateU=1/Period;

%BufferSize=[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2];
%BufferSize=[4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4];
BufferSize=[5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5];

tic;
%生成各种曲线
ServiceCurveU=rtccurve([0 0 ServiceRateU]);
ArrivalCurveU=rtccurve([0 BurstU ArrivalRate]);
Feedback=rtccurve([[0 0 0];[FeedbackDelay Inf 0]]);
ArrivalCurveL=rtccurve([[0 0 0];[Period 0 ArrivalRate]]);
ServiceCurveL=rtccurve([[0 0 0];[5*Period 0 ServiceRateL]]);

%计算R10为数据流f1和f4提供的服务曲线
SC10U=rtcscale(ServiceCurveU,0.5,0);
SC10L=rtcscale(ServiceCurveL,0.5,0);
%计算tau14
Temp14U=rtcminconv(SC10U,Feedback);
Temp14L=rtcminconv(SC10L,Feedback);
Beta14U=rtcplus(Temp14U,BufferSize(10));
Beta14L=rtcplus(Temp14L,BufferSize(10));
Tau14L=rtcmatminclos(Beta14L,0,Times);
%计算tau6
Temp6L=rtcminconv(SC10L,Feedback);
Beta6L=rtcplus(Temp6L,BufferSize(10));
Tau6L=rtcmatminclos(Beta6L,0,Times);
%计算tau15
Temp15U=rtcminconv(ServiceCurveU,Feedback);
Temp15L=rtcminconv(ServiceCurveL,Feedback);
Beta15U=rtcplus(Temp15U,BufferSize(14));
Beta15L=rtcplus(Temp15L,BufferSize(14));
Beta15U=rtcmin(Beta15U,Beta14U);
Beta15L=rtcmin(Beta15L,Beta14L);
Tau15L=rtcmatminclos(Beta15L,0,Times);
%计算tau7
Temp7L=rtcminconv(ServiceCurveL,Feedback);
Beta7L=rtcplus(Temp7L,BufferSize(6));
Beta7L=rtcmin(Beta7L,Beta6L);
Tau7L=rtcmatminclos(Beta7L,0,Times);
%计算tau16
Temp16U=rtcminconv(ServiceCurveU,Feedback);
Temp16L=rtcminconv(ServiceCurveU,Feedback);
Beta16U=rtcplus(Temp16U,BufferSize(15));
Beta16L=rtcplus(Temp16L,BufferSize(15));
Beta16U=rtcmin(Beta16U,Beta15U);
Beta16L=rtcmin(Beta16L,Beta15L);
Tau16L=rtcmatminclos(Beta16L,0,Times);
Tau16U=rtcmatminclos(Beta16U,0,Times);
%计算tau8
Temp8L=rtcminconv(ServiceCurveL,Feedback);
Beta8L=rtcplus(Temp8L,BufferSize(7));
Beta8L=rtcmin(Beta7L,Beta8L);
Tau8L=rtcmatminclos(Beta8L,0,Times);
%计算tauSource16
TempSource16L=rtcminconv(ServiceCurveL,Feedback);
BetaSource16L=rtcplus(TempSource16L,BufferSize(16));
BetaSource16L=rtcmin(BetaSource16L,Beta16L);
TauSource16L=rtcmatminclos(BetaSource16L,0,Times);
TempSource16U=rtcminconv(ServiceCurveU,Feedback);
BetaSource16U=rtcplus(TempSource16U,BufferSize(16));
BetaSource16U=rtcmin(BetaSource16U,Beta16U);
TauSource16U=rtcmatminclos(BetaSource16U,0,Times);
%计算tauSource8
TempSource8L=rtcminconv(ServiceCurveL,Feedback);
BetaSource8L=rtcplus(TempSource8L,BufferSize(8));
BetaSource8L=rtcmin(BetaSource8L,Beta8L);
TauSource8L=rtcmatminclos(BetaSource8L,0,Times);
%计算网络为数据流f4提供的服务曲线
SCLforF4=rtcminconv(TauSource8L(1),ServiceCurveL);
SCLforF4=rtcminconv(SCLforF4,Tau8L(1));
SCLforF4=rtcminconv(SCLforF4,ServiceCurveL);
SCLforF4=rtcminconv(SCLforF4,Tau7L(1));
SCLforF4=rtcminconv(SCLforF4,ServiceCurveL);
SCLforF4=rtcminconv(SCLforF4,Tau6L(1));
SCLforF4=rtcminconv(SCLforF4,ServiceCurveL);
%计算网络为数据流f1提供的服务曲线
SCLforF1=rtcminconv(TauSource16L(1),ServiceCurveL);
SCLforF1=rtcminconv(SCLforF1,Tau16L(1));
SCLforF1=rtcminconv(SCLforF1,ServiceCurveL);
SCLforF1=rtcminconv(SCLforF1,Tau15L(1));
SCLforF1=rtcminconv(SCLforF1,ServiceCurveL);
SCLforF1=rtcminconv(SCLforF1,Tau14L(1));
SCLforF1=rtcminconv(SCLforF1,ServiceCurveL);
%计算f1的端到端延迟
Y1=rtch(ArrivalCurveU,SCLforF1);
fprintf('Delay Bound for Flow I:%3.3f cycles\n',Y1);

%为f2计算tau9
Temp9L=rtcminconv(ServiceCurveL,Feedback);
Temp9U=rtcminconv(ServiceCurveU,Feedback);
Beta9L=rtcplus(Temp9L,BufferSize(5));
Beta9U=rtcplus(Temp9U,BufferSize(5));
Tau9L=rtcmatminclos(Beta9L,0,Times);
%为f2计算tau13
Temp13L=rtcminconv(ServiceCurveL,Feedback);
Temp13U=rtcminconv(ServiceCurveU,Feedback);
Beta13L=rtcplus(Temp13L,BufferSize(9));
Beta13U=rtcplus(Temp13U,BufferSize(9));
Beta13L=rtcmin(Beta13L,Beta9L);
Beta13U=rtcmin(Beta13U,Beta9U);
Tau13L=rtcmatminclos(Beta13L,0,Times);
Tau13U=rtcmatminclos(Beta13U,0,Times);
%为f2计算tau14
Temp14L=rtcminconv(ServiceCurveL,Feedback);
Temp14U=rtcminconv(ServiceCurveU,Feedback);
Beta14L=rtcplus(Temp14L,BufferSize(13));
Beta14U=rtcplus(Temp14U,BufferSize(13));
Beta14L=rtcmin(Beta14L,Beta13L);
Beta14U=rtcmin(Beta14U,Beta13U);
Tau14L=rtcmatminclos(Beta14L,0,Times);
Tau14U=rtcmatminclos(Beta14U,0,Times);
%为f2计算tau15
Temp15L=rtcminconv(ServiceCurveL,Feedback);
Temp15U=rtcminconv(ServiceCurveU,Feedback);
Beta15L=rtcplus(Temp15L,BufferSize(14));
Beta15U=rtcplus(Temp15U,BufferSize(14));
Beta15L=rtcmin(Beta15L,Beta14L);
Beta15U=rtcmin(Beta15U,Beta14U);
Tau15L=rtcmatminclos(Beta15L,0,Times);
Tau15U=rtcmatminclos(Beta15U,0,Times);
%计算f1在R15处的到达曲线
EquivalentSC16U=rtcminconv(TauSource16U(1),ServiceCurveU);
EquivalentSC16U=rtcminconv(EquivalentSC16U,Tau16U(1));
EquivalentSC16L=rtcminconv(TauSource16L(1),ServiceCurveL);
EquivalentSC16L=rtcminconv(EquivalentSC16L,Tau16L(1));
OutAC16U=rtcminconv(ArrivalCurveU,EquivalentSC16U);
OutAC16U=rtcmindeconv(OutAC16U,EquivalentSC16L);
OutAC16U=rtcmin(OutAC16U,EquivalentSC16U);
OutAC16L=rtcmindeconv(ArrivalCurveL,EquivalentSC16U);
OutAC16L=rtcminconv(OutAC16L,EquivalentSC16L);
OutAC16L=rtcmin(OutAC16L,EquivalentSC16L);
%计算R15的剩余服务曲线
LeftSC15U=rtcminus(ServiceCurveU,OutAC16L);
LeftSC15U=rtcmaxdeconv(LeftSC15U,0);
LeftSC15U=rtcmax(LeftSC15U,0);
LeftSC15U=rtcplus(LeftSC15U,1);
LeftSC15U=rtcmin(LeftSC15U,ServiceCurveU);
LeftSC15L=rtcminus(ServiceCurveL,OutAC16U);
LeftSC15L=rtcmaxconv(LeftSC15L,0);
LeftSC15L=rtcminus(LeftSC15L,1);
LeftSC15L=rtcmax(LeftSC15L,0);
%为f2计算tauSource
TempSource2L=rtcminconv(LeftSC15L,Feedback);
TempSource2U=rtcminconv(LeftSC15U,Feedback);
BetaSource2L=rtcplus(TempSource2L,BufferSize(15));
BetaSource2U=rtcplus(TempSource2U,BufferSize(15));
BetaSource2L=rtcmin(BetaSource2L,Beta15L);
BetaSource2U=rtcmin(BetaSource2U,Beta15U);
TauSource2L=rtcmatminclos(BetaSource2L,0,Times);
TauSource2U=rtcmatminclos(BetaSource2U,0,Times);
%计算f2的等效服务曲线
EquivalentSC2L=rtcminconv(TauSource2L(1),LeftSC15L);
EquivalentSC2U=rtcminconv(TauSource2U(1),LeftSC15U);
EquivalentSC2L=rtcminconv(EquivalentSC2L,Tau15L(1));
EquivalentSC2U=rtcminconv(EquivalentSC2U,Tau15U(1));
EquivalentSC2L=rtcminconv(EquivalentSC2L,ServiceCurveL);
EquivalentSC2U=rtcminconv(EquivalentSC2U,ServiceCurveU);
EquivalentSC2L14=rtcminconv(EquivalentSC2L,Tau14L(1));
EquivalentSC2U14=rtcminconv(EquivalentSC2U,Tau14U(1));
EquivalentSC2L=rtcminconv(EquivalentSC2L14,ServiceCurveL);
EquivalentSC2U=rtcminconv(EquivalentSC2U14,ServiceCurveU);
EquivalentSC2L13=rtcminconv(EquivalentSC2L,Tau13L(1));
EquivalentSC2U13=rtcminconv(EquivalentSC2U,Tau13U(1));
EquivalentSC2L=rtcminconv(EquivalentSC2L13,ServiceCurveL);
EquivalentSC2L=rtcminconv(EquivalentSC2L,Tau9L(1));
EquivalentSC2L=rtcminconv(EquivalentSC2L,ServiceCurveL);
%计算f2的端到端延迟
Y2=rtch(ArrivalCurveU,EquivalentSC2L);
fprintf('Delay Bound for Flow II:%3.3f cycles\n',Y2);

%为数据流f3计算tau5的下括服务曲线，上括不需要计算了
Temp5L=rtcminconv(ServiceCurveL,Feedback);
Beta5L=rtcplus(Temp5L,BufferSize(1));
Tau5L=rtcmatminclos(Beta5L,0,Times);
%计算tau9的服务曲线
Temp9L=rtcminconv(ServiceCurveL,Feedback);
Beta9L=rtcplus(Temp9L,BufferSize(5));
Beta9L=rtcmin(Beta9L,Beta5L);
Tau9L=rtcmatminclos(Beta9L,0,Times);
%计算f2在R9处的上括到达曲线，下括不需要计算了
AC2U9=rtcminconv(ArrivalCurveU,EquivalentSC2U13);
AC2U9=rtcmindeconv(AC2U9,EquivalentSC2L13);
AC2U9=rtcmin(AC2U9,EquivalentSC2U13);
%计算数据流f2在R9处的下括剩余服务曲线，上括不需要计算了
LeftSC9L=rtcminus(ServiceCurveL,AC2U9);
LeftSC9L=rtcmaxconv(LeftSC9L,0);
LeftSC9L=rtcminus(LeftSC9L,1);
LeftSC9L=rtcmax(LeftSC9L,0);
%计算tau13的下括服务曲线
Temp13L=rtcminconv(LeftSC9L,Feedback);
Beta13L=rtcplus(Temp13L,BufferSize(9));
Beta13L=rtcmin(Beta13L,Beta9L);
Tau13L=rtcmatminclos(Beta13L,0,Times);
%计算f2在R13处的上括到达曲线，下括不需要计算了
AC2U13=rtcminconv(ArrivalCurveU,EquivalentSC2U14);
AC2U13=rtcmindeconv(AC2U13,EquivalentSC2L14);
AC2U13=rtcmin(AC2U13,EquivalentSC2U14);
%计算数据流f2在R13处的下括剩余服务曲线，上括不需要计算了
LeftSC13L=rtcminus(ServiceCurveL,AC2U13);
LeftSC13L=rtcmaxconv(LeftSC13L,0);
LeftSC13L=rtcminus(LeftSC13L,1);
LeftSC13L=rtcmax(LeftSC13L,0);
%计算tauSource的下括服务曲线
TempSource3L=rtcminconv(LeftSC13L,Feedback);
BetaSource3L=rtcplus(TempSource3L,BufferSize(13));
BetaSource3L=rtcmin(BetaSource3L,Beta13L);
TauSource3L=rtcmatminclos(BetaSource3L,0,Times);
%计算数据流f3的等效服务曲线
SC3L=rtcminconv(TauSource3L(1),LeftSC13L);
SC3L=rtcminconv(SC3L,Tau13L(1));
SC3L=rtcminconv(SC3L,LeftSC9L);
SC3L=rtcminconv(SC3L,Tau9L(1));
SC3L=rtcminconv(SC3L,ServiceCurveL);
SC3L=rtcminconv(SC3L,Tau5L(1));
SC3L=rtcminconv(SC3L,ServiceCurveL);
%计算f3的端到端延迟
Y3=rtch(ArrivalCurveU,SC3L);
fprintf('Delay Bound for Flow III:%3.3f cycles\n',Y3);
%计算f4的端到端延迟
Y4=rtch(ArrivalCurveU,SCLforF4);
fprintf('Delay Bound for Flow IV:%3.3f cycles\n',Y4);
toc;
end